In [1]:
from tensorflow import keras
from keras.models import Model
from keras import layers
from keras.layers import Dense, Input, BatchNormalization, Activation
from keras.layers import Conv2D, SeparableConv2D, MaxPooling2D, GlobalAveragePooling2D, GlobalMaxPooling2D
#from keras.applications.imagenet_utils import _obtain_input_shape

from sklearn.model_selection import KFold
from keras.datasets import mnist
from PIL import Image
# for creating a one hot vector for labels

from IPython.display import display, Image
#import the models
from keras import Model
#add layers
from keras import layers
#add optimizer
from keras import optimizers
#add loss function 
from keras import losses

import keras
import numpy as np
import pandas as pd 
import os
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
import os
import numpy as np
import matplotlib.pyplot as plt
import cv2

2025-10-30 07:25:00.778249: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1761809100.962361      37 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1761809101.029270      37 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [2]:
"""
from keras.models import Model
from keras import layers
from keras.layers import Dense, Input, BatchNormalization, Activation
from keras.layers import Conv2D, SeparableConv2D, MaxPooling2D, GlobalAveragePooling2D, GlobalMaxPooling2D
#from keras.applications.imagenet_utils import _obtain_input_shape


#WEIGHTS_PATH = 'https://github.com/fchollet/deep-learning-models/releases/download/v0.4/xception_weights_tf_dim_ordering_tf_kernels.h5'
img_size = 299
def Xception():

	# Determine proper input shape
	input_shape = (img_size, img_size, 3 )#_obtain_input_shape(None, default_size=299, min_size=71, data_format='channels_last', include_top=False)

	img_input = Input(shape=input_shape)

	# Block 1
	x = Conv2D(32, (3, 3), strides=(2, 2), use_bias=False)(img_input)
	x = BatchNormalization()(x)
	x = Activation('relu')(x)
	x = Conv2D(64, (3, 3), use_bias=False)(x)
	x = BatchNormalization()(x)
	x = Activation('relu')(x)

	residual = Conv2D(128, (1, 1), strides=(2, 2), padding='same', use_bias=False)(x)
	residual = BatchNormalization()(residual)

	# Block 2
	x = SeparableConv2D(128, (3, 3), padding='same', use_bias=False)(x)
	x = BatchNormalization()(x)
	x = Activation('relu')(x)
	x = SeparableConv2D(128, (3, 3), padding='same', use_bias=False)(x)
	x = BatchNormalization()(x)

	# Block 2 Pool
	x = MaxPooling2D((3, 3), strides=(2, 2), padding='same')(x)
	x = layers.add([x, residual])

	residual = Conv2D(256, (1, 1), strides=(2, 2), padding='same', use_bias=False)(x)
	residual = BatchNormalization()(residual)

	# Block 3
	x = Activation('relu')(x)
	x = SeparableConv2D(256, (3, 3), padding='same', use_bias=False)(x)
	x = BatchNormalization()(x)
	x = Activation('relu')(x)
	x = SeparableConv2D(256, (3, 3), padding='same', use_bias=False)(x)
	x = BatchNormalization()(x)

	# Block 3 Pool
	x = MaxPooling2D((3, 3), strides=(2, 2), padding='same')(x)
	x = layers.add([x, residual])

	residual = Conv2D(728, (1, 1), strides=(2, 2), padding='same', use_bias=False)(x)
	residual = BatchNormalization()(residual)

	# Block 4
	x = Activation('relu')(x)
	x = SeparableConv2D(728, (3, 3), padding='same', use_bias=False)(x)
	x = BatchNormalization()(x)
	x = Activation('relu')(x)
	x = SeparableConv2D(728, (3, 3), padding='same', use_bias=False)(x)
	x = BatchNormalization()(x)

	x = MaxPooling2D((3, 3), strides=(2, 2), padding='same')(x)
	x = layers.add([x, residual])

	# Block 5 - 12
	for i in range(8):
		residual = x

		x = Activation('relu')(x)
		x = SeparableConv2D(728, (3, 3), padding='same', use_bias=False)(x)
		x = BatchNormalization()(x)
		x = Activation('relu')(x)
		x = SeparableConv2D(728, (3, 3), padding='same', use_bias=False)(x)
		x = BatchNormalization()(x)
		x = Activation('relu')(x)
		x = SeparableConv2D(728, (3, 3), padding='same', use_bias=False)(x)
		x = BatchNormalization()(x)

		x = layers.add([x, residual])

	residual = Conv2D(1024, (1, 1), strides=(2, 2), padding='same', use_bias=False)(x)
	residual = BatchNormalization()(residual)

	# Block 13
	x = Activation('relu')(x)
	x = SeparableConv2D(728, (3, 3), padding='same', use_bias=False)(x)
	x = BatchNormalization()(x)
	x = Activation('relu')(x)
	x = SeparableConv2D(1024, (3, 3), padding='same', use_bias=False)(x)
	x = BatchNormalization()(x)

	# Block 13 Pool
	x = MaxPooling2D((3, 3), strides=(2, 2), padding='same')(x)
	x = layers.add([x, residual])

	# Block 14
	x = SeparableConv2D(1536, (3, 3), padding='same', use_bias=False)(x)
	x = BatchNormalization()(x)
	x = Activation('relu')(x)

	# Block 14 part 2
	x = SeparableConv2D(2048, (3, 3), padding='same', use_bias=False)(x)
	x = BatchNormalization()(x)
	x = Activation('relu')(x)

	# Fully Connected Layer
	x = GlobalAveragePooling2D()(x)
	x = Dense( 3 , activation='softmax')(x)

	inputs = img_input

	# Create model
	model = Model(inputs, x, name='xception')

	# Download and cache the Xception weights file


	return model
"""

print("Hello world.")

Hello world.


In [3]:
"""
model = Xception()
model.compile(
    optimizer= 'Adam',
    loss= 'categorical_crossentropy',
    metrics=["accuracy"],
)
model.summary()
"""
print("Hello world.")

Hello world.


In [4]:
from keras.models import Model
from keras.layers import (
    Input, Conv2D, SeparableConv2D, MaxPooling2D, 
    GlobalAveragePooling2D, BatchNormalization, Activation, 
    Dense, Dropout, Add, Rescaling
)
from keras.optimizers import Adam
from keras import mixed_precision

# ✅ Enable mixed precision for faster GPU training (optional)
mixed_precision.set_global_policy('mixed_float16')

def Xception(input_shape=(299, 299, 3), classes=3):
    img_input = Input(shape=input_shape)

    # Normalize input to [0,1]
    x = Rescaling(1./255)(img_input)

    # ===== Entry Flow =====
    x = Conv2D(32, (3,3), strides=(2,2), use_bias=False)(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = Conv2D(64, (3,3), use_bias=False)(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    # First block
    residual = Conv2D(128, (1,1), strides=(2,2), padding='same', use_bias=False)(x)
    residual = BatchNormalization()(residual)

    x = SeparableConv2D(128, (3,3), padding='same', use_bias=False)(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = SeparableConv2D(128, (3,3), padding='same', use_bias=False)(x)
    x = BatchNormalization()(x)

    x = MaxPooling2D((3,3), strides=(2,2), padding='same')(x)
    x = Add()([x, residual])

    # Second block
    residual = Conv2D(256, (1,1), strides=(2,2), padding='same', use_bias=False)(x)
    residual = BatchNormalization()(residual)

    x = Activation('relu')(x)
    x = SeparableConv2D(256, (3,3), padding='same', use_bias=False)(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = SeparableConv2D(256, (3,3), padding='same', use_bias=False)(x)
    x = BatchNormalization()(x)

    x = MaxPooling2D((3,3), strides=(2,2), padding='same')(x)
    x = Add()([x, residual])

    # Third block
    residual = Conv2D(728, (1,1), strides=(2,2), padding='same', use_bias=False)(x)
    residual = BatchNormalization()(residual)

    x = Activation('relu')(x)
    x = SeparableConv2D(728, (3,3), padding='same', use_bias=False)(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = SeparableConv2D(728, (3,3), padding='same', use_bias=False)(x)
    x = BatchNormalization()(x)

    x = MaxPooling2D((3,3), strides=(2,2), padding='same')(x)
    x = Add()([x, residual])

    # ===== Middle Flow (8 times) =====
    for _ in range(8):
        residual = x
        # 1x1 conv to match channels if needed
        if residual.shape[-1] != 728:
            residual = Conv2D(728, (1,1), padding='same', use_bias=False)(residual)
            residual = BatchNormalization()(residual)

        x = Activation('relu')(x)
        x = SeparableConv2D(728, (3,3), padding='same', use_bias=False)(x)
        x = BatchNormalization()(x)
        x = Activation('relu')(x)
        x = SeparableConv2D(728, (3,3), padding='same', use_bias=False)(x)
        x = BatchNormalization()(x)
        x = Activation('relu')(x)
        x = SeparableConv2D(728, (3,3), padding='same', use_bias=False)(x)
        x = BatchNormalization()(x)

        x = Add()([x, residual])

    # ===== Exit Flow =====
    residual = Conv2D(1024, (1,1), strides=(2,2), padding='same', use_bias=False)(x)
    residual = BatchNormalization()(residual)

    x = Activation('relu')(x)
    x = SeparableConv2D(728, (3,3), padding='same', use_bias=False)(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)
    x = SeparableConv2D(1024, (3,3), padding='same', use_bias=False)(x)
    x = BatchNormalization()(x)
    x = MaxPooling2D((3,3), strides=(2,2), padding='same')(x)
    x = Add()([x, residual])

    x = SeparableConv2D(1536, (3,3), padding='same', use_bias=False)(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    x = SeparableConv2D(2048, (3,3), padding='same', use_bias=False)(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    # ===== Classifier =====
    x = GlobalAveragePooling2D()(x)
    x = Dropout(0.5)(x)
    x = Dense(classes, activation='softmax', dtype='float32')(x)

    model = Model(img_input, x, name='xception_custom')
    return model


# ===== Compile Model =====
model = Xception(input_shape=(299, 299, 3), classes=3)
model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# View model summary
model.summary()


I0000 00:00:1761809114.356342      37 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13942 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1761809114.357081      37 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13942 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5


Model: "xception_custom"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 299, 299,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cast (Cast)         │ (None, 299, 299,  │          0 │ input_layer[0][0] │
│                     │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ rescaling           │ (None, 299, 299,  │          0 │ cast[0][0]        │
│ (Rescaling)         │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d (Conv2D)     │ (None, 149, 149,  │        864 │ rescaling[0][0]   │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 149, 149,  │        128 │ conv2d[0][0]      │
│ (BatchNormalizatio… │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation          │ (None, 149, 149,  │          0 │ batch_normalizat… │
│ (Activation)        │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_1 (Conv2D)   │ (None, 147, 147,  │     18,432 │ activation[0][0]  │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 147, 147,  │        256 │ conv2d_1[0][0]    │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_1        │ (None, 147, 147,  │          0 │ batch_normalizat… │
│ (Activation)        │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ separable_conv2d    │ (None, 147, 147,  │      8,768 │ activation_1[0][… │
│ (SeparableConv2D)   │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 147, 147,  │        512 │ separable_conv2d… │
│ (BatchNormalizatio… │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_2        │ (None, 147, 147,  │          0 │ batch_normalizat… │
│ (Activation)        │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ separable_conv2d_1  │ (None, 147, 147,  │     17,536 │ activation_2[0][… │
│ (SeparableConv2D)   │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 147, 147,  │        512 │ separable_conv2d… │
│ (BatchNormalizatio… │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_2 (Conv2D)   │ (None, 74, 74,    │      8,192 │ activation_1[0][… │
│                     │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d       │ (None, 74, 74,    │          0 │ batch_normalizat… │
│ (MaxPooling2D)      │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 74, 74,    │        512 │ conv2d_2[0][0]  

 Total params: 20,867,627 (79.60 MB)

 Trainable params: 20,813,099 (79.40 MB)

 Non-trainable params: 54,528 (213.00 KB)

In [5]:
import os
x = []
label = []
x_validation = []
label_validation = []
x_test = []
label_test = []
img_size = 299

image_link = "/kaggle/input/malabar-dataset/Malabar_Dataset/Anthracnose(102)"
image_list = os.listdir(image_link)
print(len(image_list))

for i in range(0, len(os.listdir(image_link))):
    if i < 80:
        image = cv2.imread(image_link + '/' + image_list[i])
        image = cv2.resize(image , ( img_size , img_size ))
        x.append(image)
        label.append([0])
    elif i < 90:
        image = cv2.imread(image_link + '/' + image_list[i])
        image = cv2.resize(image , ( img_size , img_size ))
        x_validation.append(image)
        label_validation.append([0])
    else:
        image = cv2.imread(image_link + '/' + image_list[i])
        image = cv2.resize(image , ( img_size , img_size ))
        x_test.append(image)
        label_test.append([0])
        

print(len(x))
print(len(x_validation))
print(len(x_test))

102
80
10
12


In [6]:
image_link = "/kaggle/input/malabar-dataset/Malabar_Dataset/Bacterial-Spot(752)"
image_list = os.listdir(image_link)
print(len(image_list))

for i in range(0, len(os.listdir(image_link))):
    if i < 601:
        image = cv2.imread(image_link + '/' + image_list[i])
        image = cv2.resize(image , ( img_size , img_size ))
        x.append(image)
        label.append([1])
    elif i < 676:
        image = cv2.imread(image_link + '/' + image_list[i])
        image = cv2.resize(image , ( img_size , img_size ))
        x_validation.append(image)
        label_validation.append([1])
    else:
        image = cv2.imread(image_link + '/' + image_list[i])
        image = cv2.resize(image , ( img_size , img_size ))
        x_test.append(image)
        label_test.append([1])
        

print(len(x))
print(len(x_validation))
print(len(x_test))

752
681
85
88


In [7]:
image_link = "/kaggle/input/malabar-dataset/Malabar_Dataset/Downy-Mildew(240)"
image_list = os.listdir(image_link)
print(len(image_list))

for i in range(0, len(os.listdir(image_link))):
    if i < 601:
        image = cv2.imread(image_link + '/' + image_list[i])
        image = cv2.resize(image , ( img_size , img_size ))
        x.append(image)
        label.append([2])
    elif i < 676:
        image = cv2.imread(image_link + '/' + image_list[i])
        image = cv2.resize(image , ( img_size , img_size ))
        x_validation.append(image)
        label_validation.append([2])
    else:
        image = cv2.imread(image_link + '/' + image_list[i])
        image = cv2.resize(image , ( img_size , img_size ))
        x_test.append(image)
        label_test.append([2])
        

print(len(x))
print(len(x_validation))
print(len(x_test))

240
921
85
88


In [8]:
x = np.asarray(x)
x_validation = np.asarray(x_validation)
x_test = np.asarray(x_test)

print(len(x)," ", len(x_validation)," ", len(x_test))

921   85   88


In [9]:
from tensorflow import keras


label = keras.utils.to_categorical(label, num_classes=3)
print(len(label))
print(label)


label_validation = keras.utils.to_categorical(label_validation, num_classes=3)
print(len(label_validation))
print(label_validation)


label_test = keras.utils.to_categorical(label_test, num_classes=3)
print(len(label_test))
print(label_test)

921
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
85
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0

In [10]:
early_stop  = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience= 40 , verbose=0, mode='max')
check_point = tf.keras.callbacks.ModelCheckpoint('./Xception_malabar_dataset.h5', monitor='val_accuracy', save_best_only=True, mode='max')
history = model.fit(x , label , validation_data = (x_validation , label_validation ), epochs = 60 , callbacks=[early_stop, check_point])
    

print("skip")

Epoch 1/60


I0000 00:00:1761809171.107513      99 service.cc:148] XLA service 0x7bcb2881ce80 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1761809171.108309      99 service.cc:156]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
I0000 00:00:1761809171.108340      99 service.cc:156]   StreamExecutor device (1): Tesla T4, Compute Capability 7.5
I0000 00:00:1761809175.133745      99 cuda_dnn.cc:529] Loaded cuDNN version 90300
2025-10-30 07:26:28.620576: E external/local_xla/xla/service/slow_operation_alarm.cc:65] Trying algorithm eng0{} for conv (f16[32,149,149,32]{3,2,1,0}, u8[0]{0}) custom-call(f16[32,147,147,64]{3,2,1,0}, f16[64,3,3,32]{3,2,1,0}), window={size=3x3}, dim_labels=b01f_o01i->b01f, custom_call_target="__cudnn$convBackwardInput", backend_config={"cudnn_conv_backend_config":{"activation_mode":"kNone","conv_result_scale":1,"leakyrelu_alpha":0,"side_input_scale":0},"force_earliest_schedule":false,"operation_queue_id":"0","

28/29 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step - accuracy: 0.5831 - loss: 0.8859

2025-10-30 07:27:27.864629: E external/local_xla/xla/service/slow_operation_alarm.cc:65] Trying algorithm eng0{} for conv (f16[25,149,149,32]{3,2,1,0}, u8[0]{0}) custom-call(f16[25,147,147,64]{3,2,1,0}, f16[64,3,3,32]{3,2,1,0}), window={size=3x3}, dim_labels=b01f_o01i->b01f, custom_call_target="__cudnn$convBackwardInput", backend_config={"cudnn_conv_backend_config":{"activation_mode":"kNone","conv_result_scale":1,"leakyrelu_alpha":0,"side_input_scale":0},"force_earliest_schedule":false,"operation_queue_id":"0","wait_on_operation_queues":[]} is taking a while...
2025-10-30 07:27:27.969333: E external/local_xla/xla/service/slow_operation_alarm.cc:133] The operation took 1.104815319s
Trying algorithm eng0{} for conv (f16[25,149,149,32]{3,2,1,0}, u8[0]{0}) custom-call(f16[25,147,147,64]{3,2,1,0}, f16[64,3,3,32]{3,2,1,0}), window={size=3x3}, dim_labels=b01f_o01i->b01f, custom_call_target="__cudnn$convBackwardInput", backend_config={"cudnn_conv_backend_config":{"activation_mode":"kNone","con

29/29 ━━━━━━━━━━━━━━━━━━━━ 154s 2s/step - accuracy: 0.5905 - loss: 0.8751 - val_accuracy: 0.8824 - val_loss: 1.0628
Epoch 2/60
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 220ms/step - accuracy: 0.7917 - loss: 0.5207 - val_accuracy: 0.8824 - val_loss: 1.0390
Epoch 3/60
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 224ms/step - accuracy: 0.8216 - loss: 0.4110 - val_accuracy: 0.8824 - val_loss: 1.0131
Epoch 4/60
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 227ms/step - accuracy: 0.8719 - loss: 0.3315 - val_accuracy: 0.8824 - val_loss: 0.9884
Epoch 5/60
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 230ms/step - accuracy: 0.9139 - loss: 0.2413 - val_accuracy: 0.8824 - val_loss: 0.9572
Epoch 6/60
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 232ms/step - accuracy: 0.9622 - loss: 0.1165 - val_accuracy: 0.8824 - val_loss: 0.9112
Epoch 7/60
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 232ms/step - accuracy: 0.9769 - loss: 0.0754 - val_accuracy: 0.8824 - val_loss: 0.8716
Epoch 8/60
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 235ms/step - accuracy: 0.9993 - loss: 0.0141 - val_accuracy: 0.8824 - val_l

In [ ]:
while(True):
    a = 5

In [11]:
extract_saved_Xception_model = tf.keras.models.load_model('./Xception_malabar_dataset.h5') 
extract_saved_Xception_model.summary()

ValueError: Unknown layer: 'Cast'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

In [ ]:
loss, acc = extract_saved_Xception_model.evaluate(x_test, label_test, verbose=2)
print('Restored model, accuracy: {:5.2f}%'.format(100 * acc))